spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: portfolio
    password: portfolio
  data:
    redis:
      host: localhost
  kafka:
    bootstrap-servers: localhost:29092

security:
  jwt:
    secret: local-development-secret-change-me-please

logging:
  level:
    org.apache.kafka: error
    org.apache.kafka.clients.NetworkClient: error
